### ISSUE TITLE
Feature Request - Other DEs

### ISSUE THREAD

**Issue by Justinzobel** [calo001/fondo#36]
Love the app. Just wondering if it was possible to have it work with other desktops like KDE Plasma?

**Comment by terndrup** [comment]
You can probably get it to work on a KDE desktop using a containerised version like a Flatpak:

https://flathub.org/apps/details/com.github.calo001.fondo

But it will likely be loading lots of GNOME GTK dependencies so it may not be ideal

**Comment by tim77** [comment]
In Fedora Xfce Spin it requires very few dependencies to install `dee, granite, libunity`. 3.3 Mb overall install size. But this RPM package not Flatpak version. Flatpak version need Gnome runtime which is about ~1 Gb.

**Comment by matrixise** [comment]
hi and for i3, swaywm etc...  in fact with these WM, we need to know the location of the wallpaper.

**Comment by Justinzobel** [comment]
Flatpak installed and run. Cannot set wallpaper though, it pops up showing "Your new wallpaper is ready!" but the wallpaper does not change.

OS: Solus
DE: Plasma

![image](https://user-images.githubusercontent.com/1370117/56891829-e29f5700-6abc-11e9-9932-f3977cece02a.png)

**Comment by Justinzobel** [comment]
The only error of sorts I see when running it from a terminal is "Greeter not found". All other output is it downloading images.

**Comment by ayanb1991** [comment]
> Flatpak installed and run. Cannot set wallpaper though, it pops up showing "Your new wallpaper is ready!" but the wallpaper does not change.
> 
> OS: Solus
> DE: Plasma
> 
> Edit: Also note crazy large black border around it.
> 
> ![image](https://user-images.githubusercontent.com/1370117/56891829-e29f5700-6abc-11e9-9932-f3977cece02a.png)

Yup. Same here on KDE Neon. Installed from Flatpak.

**Comment by bilelmoussaoui** [comment]
This should be fixed once the wallpaper portal is ready.

**Comment by All3xJ** [comment]
Issue still there. KDE 5.23.
With git version from AUR it simly does not work.
With flatpak version it gives me this:
https://i.imgur.com/UvgXpzG.png

Question: what is the Fondo wallpaper folder so that I can manually set the wallpaper?
